# Generated by Django 3.1.2 on 2020-11-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tripeando', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id_post',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
