# Generated by Django 3.1.2 on 2020-11-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tripeando', '0004_auto_20201103_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='id_comentarios',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lugares',
            name='id_lugares',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='respuesta_comentarios',
            name='id_respuesta_c',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rrss',
            name='id_rs',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario_rrss',
            name='id_usuario_rrss',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
