# Generated by Django 3.1.2 on 2020-11-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tripeando', '0005_auto_20201103_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='usuario',
            new_name='usuario2',
        ),
    ]
