# Generated by Django 3.1.2 on 2020-11-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tripeando', '0007_auto_20201103_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha_publicacion']},
        ),
    ]
