# Generated by Django 3.1.2 on 2020-11-09 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tripeando', '0009_auto_20201109_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['-fecha_comentario']},
        ),
        migrations.AddField(
            model_name='comentarios',
            name='fecha_comentario',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
