# Generated by Django 3.1.2 on 2020-11-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tripeando', '0010_auto_20201109_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_seguridad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
