# Generated by Django 3.1.2 on 2020-11-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tripeando', '0011_usuario_codigo_seguridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo_seguridad',
            field=models.CharField(max_length=30),
        ),
    ]
