# Generated by Django 3.1.2 on 2020-11-27 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tripeando', '0014_auto_20201109_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='codigo_seguridad',
        ),
    ]
