# Generated by Django 3.1.2 on 2020-11-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tripeando', '0002_auto_20201103_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
